### ISSUE TITLE
This issue vue.js les (Versie verschil misschien)

### ISSUE THREAD

**Issue by enricostrijks** [enricostrijks/vue-steam-wishlist#1]
https://github.com/enricostrijks/vue-steam-wishlist/blob/6f10758a1587f70a35678c679bc445b4264cd650/src/components/SteamWishlistItem.vue#L19

**Comment by Theo-denBlanken** [comment]
Wat was nu ook al weer de foutmelding?

**Comment by enricostrijks** [comment]
error    Unexpected mutation of "wishlists" prop  vue/no-mutating-props

**Comment by Theo-denBlanken** [comment]
Ja ik denk wel dat het een probleem met de versie is. gebruik dus 2.
Maak daarvoor een nieuw project aan.

Daarnaast vindt ik 'whislist_s_' nogal verwarrend in deze context, maar dat is bij jou ook al ontstaan vanuit die verkeerde versie van Vue. Er is niet zozeer sprake van meerdere wenslijsten, maar van meerdere wensen op een lijst: whishlist > wish. Die kan dan eigenschappen hebben als een id, titel en plaatje.
